function doGet(e){return api_(e)}
function doPost(e){return api_(e)}
const CFG={ID:'1skr_nxM-C5Jj9jwOC1BIxsG7XZ_e3jmQRu0HEf4NcEs',UNIT:'SMA',TYPE:'mukim',RAW:'Data_Nilai_Raport',TTL:21600};
function api_(e){const l=LockService.getScriptLock();l.waitLock(10000);try{const p=parse_(e),a=String(p.action||'health');if(a==='health'||a==='test')return out_({status:'success',success:true,unit:'SMA',schoolType:'mukim',timestamp:new Date().toISOString()});if(a==='verifyAdmin')return admin_(p);if(a==='verifyTeacherPin')return teacher_(p);if(a==='readScores'||a==='getAll'){auth_(p);return read_(p)}if(a==='updateScore'){auth_(p);return write_(p)}return out_({status:'error',success:false,message:'Action tidak dikenal: '+a})}catch(err){return out_({status:'error',success:false,message:String(err.message||err)})}finally{l.releaseLock()}}
function parse_(e){if(e&&e.postData&&e.postData.contents){try{return JSON.parse(e.postData.contents)}catch(_){} }return e&&e.parameter||{}}
function ps_(){return PropertiesService.getScriptProperties()}
function hash_(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8).map(function(b){b=b<0?b+256:b;return('0'+b.toString(16)).slice(-2)}).join('')}
function nk_(v){return String(v||'').trim().replace(/\\s+/g,' ').toUpperCase()}
function pk_(n,u,r){return'TEACHER_PIN_'+nk_(n).replace(/[^A-Z0-9]+/g,'_')+'_'+String(u||'SMA').toUpperCase()+'_'+String(r||'guru').toLowerCase()}
function setAdminPin(pin){if(String(pin).length<6)throw new Error('PIN admin minimal 6 karakter');ps_().setProperty('ADMIN_PIN_SHA256',hash_(pin));return'OK'}
function setTeacherPin(name,unit,role,pin){if(String(unit).toUpperCase()!=='SMA')throw new Error('Hanya SMA');if(!/^\\d{4,12}$/.test(String(pin)))throw new Error('PIN harus 4-12 digit');ps_().setProperty(pk_(name,unit,role),hash_(pin));return'OK'}
function admin_(p){const h=ps_().getProperty('ADMIN_PIN_SHA256')||'';if(!h)return out_({status:'error',success:false,message:'ADMIN PIN belum dikonfigurasi'});if(hash_(String(p.pin||''))!==h)return out_({status:'success',success:false});return session_('admin','admin')}
function teacher_(p){const u=String(p.unit||'').toUpperCase(),r=String(p.role||'guru').toLowerCase(),n=String(p.teacherName||'').trim();if(u!=='SMA')return out_({status:'success',success:false,message:'SMP belum diaktifkan'});const h=ps_().getProperty(pk_(n,u,r))||'';if(!h||hash_(String(p.pin||''))!==h)return out_({status:'success',success:false,authenticated:false});return session_(n,r)}
function session_(id,role){const t=Utilities.getUuid();CacheService.getScriptCache().put('RAPORT_V51_'+t,JSON.stringify({id:id,role:role,unit:'SMA'}),CFG.TTL);return out_({status:'success',success:true,authenticated:true,sessionToken:t,expiresInSeconds:CFG.TTL})}
function auth_(p){const t=String(p.adminSessionToken||p.teacherSessionToken||'').trim();if(!t)throw new Error('Sesi login tidak ditemukan');const v=CacheService.getScriptCache().get('RAPORT_V51_'+t);if(!v)throw new Error('Sesi login sudah berakhir');return JSON.parse(v)}
function scope_(p){if(String(p.unit||'SMA').toUpperCase()!=='SMA')throw new Error('Backend hanya menerima Pondok SMA');if(String(p.schoolType||'mukim').toLowerCase()!=='mukim')throw new Error('Backend hanya menerima Pondok Mukim SMA')}
function raw_(){const ss=SpreadsheetApp.openById(CFG.ID);let s=ss.getSheetByName(CFG.RAW);if(!s){s=ss.insertSheet(CFG.RAW);s.getRange(1,1,1,8).setValues([['ID Santri','ID Kelas','Nama','NISN','ID Mapel','Nama Mapel','Nilai','Updated At']]);s.setFrozenRows(1)}return s}
function read_(p){scope_(p);const cid=String(p.classId||'').trim(),s=raw_(),v=s.getDataRange().getValues(),o={};for(let i=1;i<v.length;i++){const r=v[i],sid=String(r[0]||'').trim(),c=String(r[1]||'').trim(),sub=String(r[4]||'').trim(),sc=r[6];if(!sid||!sub||sc===''||isNaN(Number(sc))||cid&&c!==cid)continue;(o[sid]||(o[sid]={}))[sub]=Number(sc)}return out_({status:'success',success:true,unit:'SMA',schoolType:'mukim',classId:cid,studentsScores:o,rowCount:Object.keys(o).length,timestamp:new Date().toISOString()})}
function write_(p){scope_(p);const sid=String(p.studentId||'').trim(),cid=String(p.classId||'').trim(),sub=String(p.subjectId||'').trim(),sc=Number(p.score);if(!sid||!cid||!sub)throw new Error('studentId, classId, subjectId wajib');if(!isFinite(sc)||sc<0||sc>100)throw new Error('Nilai harus 0-100');const s=raw_(),v=s.getDataRange().getValues(),now=Utilities.formatDate(new Date(),'Asia/Jakarta','yyyy-MM-dd HH:mm:ss'),row=[sid,cid,String(p.studentName||''),String(p.nisn||''),sub,String(p.subjectName||''),sc,now];let target=0;for(let i=1;i<v.length;i++)if(String(v[i][0])===sid&&String(v[i][1])===cid&&String(v[i][4])===sub){target=i+1;break}if(target)s.getRange(target,1,1,8).setValues([row]);else s.getRange(s.getLastRow()+1,1,1,8).setValues([row]);return out_({status:'success',success:true,saved:true,studentId:sid,subjectId:sub,updatedAt:now})}
function out_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}